
const news = [
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Megapod of feeding humpback whales 'so special'","description":"More than 100 humpback whales have been filmed feeding off Australia's New South Wales coast.","url":"http://www.bbc.co.uk/news/world-australia-58552939","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/58EB/production/_120536722_p09vwkq8.jpg","publishedAt":"2021-09-14T15:22:37.487223Z","content":"A megapod of more than 100 humpback whales has been filmed feeding off the New South Wales coast of Australia.\r\nSpeaking to the BBC, Dr Jen Jackson, from the British Antarctic Survey, welcomed increa… [+176 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Cows toilet trained to reduce greenhouse gas emissions","description":"Researchers say toilet training cows could lead to a large reduction in ammonia emissions.","url":"http://www.bbc.co.uk/news/world-europe-58552651","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/4546/production/_120543771_acalfentersalatrinecreditfbn.jpg","publishedAt":"2021-09-14T15:22:28.8487479Z","content":"media captionA cow uses a MooLoo as part of an experiment\r\nCows can be toilet trained in order to reduce greenhouse gas emissions, researchers have said.\r\nIn the study, which took place in Germany, s… [+1752 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Met Gala: 13 of the most eye-catching looks","description":"Jennifer Lopez, Simone Biles, Dan Levy, Ella Emhoff and Tommy Hilfiger were all on the red carpet.","url":"http://www.bbc.co.uk/news/entertainment-arts-58537575","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/2090/production/_120563380_rihannareu.jpg","publishedAt":"2021-09-14T15:22:25.8807357Z","content":"By Steven McIntoshEntertainment reporter\r\nimage source, Getty Images\r\nimage captionJustin and Hailey Bieber were among the stars posing on the red carpet\r\nThere were so many celebrities on the red ca… [+11143 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"China's coronavirus-fuelled surfing boom","description":"Covid restrictions that have limited foreign travel have led to a boom in surfing in China.","url":"http://www.bbc.co.uk/news/world-asia-58552057","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/13F63/production/_120536718_p09vw0v7.jpg","publishedAt":"2021-09-14T10:22:22.8918895Z","content":"Chinese youth are discovering surfing in increasing numbers, thanks in part to restrictions on foreign travel in the wake of the pandemic.\r\nBBC China correspondent Stephen McDonell travelled to Haina… [+91 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Canada federal election: A look at the key numbers driving the campaign","description":"A visual guide to the big issues in Canada's federal election, from climate to cost of living.","url":"http://www.bbc.co.uk/news/world-us-canada-58426147","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/0FCC/production/_120544040_trudeau_976reuters.jpg","publishedAt":"2021-09-14T10:22:18.5023571Z","content":"By Jessica Murphy and Mike HillsBBC News\r\nimage source, NurPhoto via Getty Images)\r\nCanadians go to the polls on 20 September after a short 35-day election campaign sprint. \r\nPrime Minister Justin Tr… [+7169 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Hurricane Nicholas brings heavy rain to Texas and Louisiana","description":"Meteorologists warn of life-threatening flooding, power outages and storm surges.","url":"http://www.bbc.co.uk/news/world-us-canada-58555227","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/11D40/production/_120542037_hi070599246-1.jpg","publishedAt":"2021-09-14T08:07:23.0496104Z","content":"image captionNicholas is carrying maximum sustained winds of 75 miles (120 km) per hour\r\nHurricane Nicholas has made landfall on the Texas coast in the US, bringing heavy rain and the risk of life-th… [+1854 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Climate change: Young people very worried - survey","description":"Over half of respondents in a survey believe humanity is doomed and governments are failing to act.","url":"http://www.bbc.co.uk/news/world-58549373","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/124B/production/_120538640_gettyimages-1206377932.jpg","publishedAt":"2021-09-14T05:22:23.4632665Z","content":"By Roger HarrabinBBC environment analyst\r\nimage source, Getty Images\r\nimage captionOver half of those surveyed said they thought humanity was doomed and that governments were failing to respond adequ… [+3784 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Apple rushes to block 'zero-click' iPhone spyware","description":"The flaw allows hackers to access devices even if users do not click on a link or file.","url":"http://www.bbc.co.uk/news/business-58540936","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/151C/production/_120540450_gettyimages-1235056717.jpg","publishedAt":"2021-09-14T03:52:22.5991045Z","content":"image source, Getty Images\r\nApple has issued a software patch to block so-called \"zero-click\" spyware that could infect iPhones and iPads.\r\nIndependent researchers identified the flaw, which lets hac… [+2596 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Climate change: World now sees twice as many days over 50C","description":"BBC research finds the number of days passing 50C has doubled in the past 40 years.","url":"http://www.bbc.co.uk/news/science-environment-58494641","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/BCDD/production/_120494384_lifeat50c_promo_976.png","publishedAt":"2021-09-14T01:37:25.0778101Z","content":"By Becky Dale &amp; Nassos StylianouData journalists\r\nThe number of extremely hot days every year when the temperature reaches 50C has doubled since the 1980s, a global BBC analysis has found.\r\nThey … [+7508 chars]"},
    {"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"California recall election: Biden campaigns with Newsom ahead of rare vote","description":"Joe Biden's first trip to the state as president comes on the eve of a gubernatorial recall vote.","url":"http://www.bbc.co.uk/news/world-us-canada-58553704","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/166F5/production/_120539819_gettyimages-1235239225-1.jpg","publishedAt":"2021-09-14T01:22:22.909421Z","content":"image source, Getty Images\r\nimage captionMr Newsom and Mr Biden\r\nPresident Joe Biden has made his first trip to California on the eve of a rare state recall election to shore up support for Governor … [+2237 chars]"}
]
export default news;